version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.7.0

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run: NODE_ENV=production yarn build:prod 


  deploy:
    machine:
      enabled: true
    steps:

      - add_ssh_keys:
          fingerprints:
            - "SHA256:6B9tBf5pntXfAybWeIJ7cQT7/XMzutdBFBITTLS1cjE"        
      - run:
          scp -oStrictHostKeyChecking=no -r -P $SSH_PORT dist/* $SSH_USER@$SSH_HOST:$DEPLOY_FOLDER


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master     